### ISSUE TITLE
Bad Docs

### ISSUE THREAD

**Issue by jpgutti** [vtex-apps/store-form#9]
The Docs says about the Schema that we can get through the Master Data API, but it doesn't make clear where we are supposed to place it...

In the manifest?
Inside the store folder as JSON?

Where?

**Comment by klzns** [comment]
Thanks for the feedback!  There's some instructions on how to do that here:
![image](https://user-images.githubusercontent.com/284515/81436056-2d779400-913f-11ea-9129-9b04f2c1cf2b.png)

Pointing to this article: https://vtex.io/docs/recipes/templates/creating-a-native-form-for-your-store-users/

Do you suggest placing this info elsewhere in this docs?
